### ISSUE TITLE
cannot build greenworks

### ISSUE THREAD

**Issue by JohnnySheffield** [greenheartgames/greenworks#1]
I'm currently writing a Construct 2 plugin based on greenworks. I'm done on C2 side with a simple test, currently i'm trying to build greenworks with node-gyp for windows.

I have installed all depedencies for node-gyp, following this: https://github.com/TooTallNate/node-gyp/wiki/Visual-Studio-2010-Setup.

When i try to build it, i get this:

``` cmd
PS C:\Users\MaliJuda\Documents\steam_plugin\greenworks-master> node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.21 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\MaliJuda\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\MaliJuda\\Documents\\steam_plugin\\greenworks-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\MaliJuda\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\MaliJuda\\.node-gyp\\0.10.21\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\MaliJuda\\.node-gyp\\0.10.21',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\MaliJuda\\Documents\\steam_plugin\\greenworks-master',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\MaliJuda\\Documents\\steam_plugin\\greenworks-master\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  move_node_module
  The system cannot find the file specified.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited w
ith code 1. [C:\Users\MaliJuda\Documents\steam_plugin\greenworks-master\build\action_after_build.vcxproj]
  main.cpp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc [C:\Users\MaliJuda\Documents\steam_plugin\greenworks-master\build\
greenworks.vcxproj]
..\main.cpp(5): fatal error C1083: Cannot open include file: 'C:\Users\MaliJuda\Documents\steam_plugin\greenworks-maste
r/steamworks-sdk/public/steam/steam_api.h': No such file or directory [C:\Users\MaliJuda\Documents\steam_plugin\greenwo
rks-master\build\greenworks.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\MaliJuda\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:267:
23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Users\\MaliJuda\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR! cwd C:\Users\MaliJuda\Documents\steam_plugin\greenworks-master
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok

```

I've googled, found and tried to apply a lot of different solutions but with no luck. 

I'm using a 64-bit version of node, could it be that my setup is wrong? 

Could you provide a more detailed guide on building greenworks on Windows? 

Thanks in advance!

**Comment by dganzella** [comment]
https://github.com/greenheartgames/greenworks/blob/master/docs/get-steamworks-sdk.md

this is the solution.
