### ISSUE TITLE
Upgrade to steam SDK v1.39

### ISSUE THREAD

**Issue by Zamiell** [greenheartgames/greenworks#115]
I'm following along with the docs step by step, trying to compile the latest version of Greenworks with the `electron-quick-start` repository.

After running
```
D:\Repositories\electron-quick-start\node_modules\greenworks>set HOME=C:\Users\j
ames\.electron-gyp && node-gyp rebuild --target=1.4.13 --arch=x64 --dist-url=htt
ps://atom.io/download/atom-shell
```

I get this:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.9.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\james\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Repositories\\electron-quick-start\\node_modules\\greenworks\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\james\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\james\\.node-gyp\\iojs-1.4.13\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\james\\.node-gyp\\iojs-1.4.13',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\james\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Repositories\\electron-quick-start\\node_modules\\greenworks',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Repositories\\electron-quick-start\\node_modules\\greenworks\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ioapi.c
  iowin32.c
  unzip.c
  zip.c
  win_delay_load_hook.cc
  minizip.vcxproj -> D:\Repositories\electron-quick-start\node_modules\greenworks\build\Release\\minizip.lib
  adler32.c
  compress.c
  crc32.c
  deflate.c
  gzclose.c
  gzlib.c
  gzread.c
  gzwrite.c
  infback.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  uncompr.c
  zutil.c
  win_delay_load_hook.cc
  zlib.vcxproj -> D:\Repositories\electron-quick-start\node_modules\greenworks\build\Release\\zlib.lib
  greenworks_api_utils.cc
  steam_api_achievement.cc
  steam_api_auth.cc
  steam_api_cloud.cc
  steam_api_friends.cc
  steam_api_settings.cc
  steam_api_workshop.cc
  greenworks_api.cc
..\src\api\steam_api_friends.cc(33): error C2065: 'k_EFriendFlagSuggested': undeclared identifier [D:\Repositories\electron-quick-start\node_modules\greenworks\build\greenworks-win64.vcxproj]
..\src\api\steam_api_friends.cc(33): error C2661: 'v8::Object::Set': no overloaded function takes 1 arguments [D:\Repositories\electron-quick-start\node_modules\greenworks\build\greenworks-win64.vcxproj]
  greenworks_async_workers.cc
  greenworks_unzip.cc
  greenworks_utils.cc
  greenworks_workshop_workers.cc
  greenworks_zip.cc
  steam_async_worker.cc
  steam_client.cc
  steam_event.cc
  steam_id.cc
  win_delay_load_hook.cc
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\james\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\james\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.4.13" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd D:\Repositories\electron-quick-start\node_modules\greenworks
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
```

I'm assuming that this is because I'm using v1.39 of the SDK, and the docs mention needing 1.38a.
(But I guess that this is not necessarily true.)

As an aside, is there a way to download old versions of the Steamworks SDK? How exactly does one get a hold of specifically version 1.38a???

**Comment by hokein** [comment]
@Zamiell From your error message, steam sdk 1.39 has breaking changes, you have to use v1.38a for a temporary fix. I will update Greenworks to the latest steam sdk. 

You can download steam v1.38a from https://partner.steamgames.com/downloads/steamworks_sdk_138a.zip.

**Comment by Zamiell** [comment]
For some reason, that URL wasn't showing up in Google. Thank you! I've managed to build it successfully now on Windows.

**Comment by Zamiell** [comment]
Hokein - I have a completely unrelated question. (Sorry, not sure where the best place for this is.)

After building it, I'm trying the following "Hello World"-style program with Greenworks + `electron-quick-start`:

```
if (greenworks.initAPI()) {
    console.log('Steam API has been initialized.');
} else {
    console.log('Error on initializing Steam API.');
    return;
}
console.log(greenworks.getSteamId().steamId);
console.log(greenworks.getSteamId().screenName);
greenworks.getAuthSessionTicket(function(ticket) {
    console.log(ticket);
}, function(err) {
    console.log(err);
});
```

It successfully prints my `steamID` and my `screenName`, but the `getAuthSessionTicket` function never fires. (The ticket doesn't log to the screen AND no errors log to the screen.)

I also tried it with the `getEncryptedAppTicket` function in exactly the way it says in [the official "Authentication" docs here](https://github.com/greenheartgames/greenworks/blob/master/docs/authentication.md), but that doesn't seem to fire either.

Any idea of what's wrong?

(My `steam_appid.txt` file contains `480`, the app ID of Space Wars. I don't think it should matter what I have in there for this particular sample program?)

**Comment by hokein** [comment]
@Zamiell For electron, you need call `process.activateUvLoop()` before greenworks.initAPI()` otherwise the eventloop of greenworks won't get run #61.

**Comment by hokein** [comment]
I'm closing this issue now as greenworks can be compiled with steamworks SDK 1.39 (Thanks to @MadSpyxFR).

**Comment by Zamiell** [comment]
Awesome, thanks so much Hokein / MadSpyxFR!

Please consider adding a note about the `process.activateUvLoop()` fix to the README.md file at the root of the repo. This is a thing that is going to throw all of your Electron users for a spin.

It should also be documented in the Wiki - I did a quick search for activateUvLoop, and there doesn't seem to be anything about it.
