### ISSUE TITLE
Greenworks doesn't work on Electron 1.6.1

### ISSUE THREAD

**Issue by Zamiell** [greenheartgames/greenworks#124]
Platform: Windows 7 Professional

Steps to reproduce:

- Follow the "Electron Building Steps" tutorial in `readme.md`, but change the `electron` version to 1.6.1 before installing Greenworks.
- Upon doing `npm start`, we see that it can't find the Greenworks module.
- So, we can try recompiling for the specific version by doing a `set HOME=~/.electron-gyp && node-gyp rebuild --target=1.6.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell`:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.9.4 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\james\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Repositories\\electron-quick-start\\node_modules\\greenworks\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\james\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\james\\.node-gyp\\iojs-1.6.1\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\james\\.node-gyp\\iojs-1.6.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\james\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Repositories\\electron-quick-start\\node_modules\\greenworks',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Repositories\\electron-quick-start\\node_modules\\greenworks\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [D:\Repositories\electron-quick-start\node_modules\greenworks\build\deps\zlib\minizip.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [D:\Repositories\electron-quick-start\node_modules\greenworks\build\deps\zlib\zlib.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\james\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\james\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.1" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd D:\Repositories\electron-quick-start\node_modules\greenworks
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
```

So, looks like errors relating to:
1) `deps\zlib\minizip.vcxproj`
2) `deps\zlib\zlib.vcxproj`

I guess this is a problem with the new version of Electron? Not 100% sure, but I have had success in building Electron in the past.

(Also, there is a typo in the readme. Change:
`cp node_modules/greenworks/sample/electron/main.js renderer.js`
to
`cp node_modules/greenworks/samples/electron/main.js renderer.js`
Thanks.)

**Comment by Zamiell** [comment]
Ok, well I reformatted my computer, did a `npm install --global windows-build-tools`, and now it compiles/rebuilds successfully, so I guess the problem was on my end. Sorry for the confusion!
