### ISSUE TITLE
Greenworks with NW.js 0.24, building with nw-gyp: "Invalid Version: undefined"

### ISSUE THREAD

**Issue by koobazaur** [greenheartgames/greenworks#154]
Hey folks,

I'm new to using NPM and the tools, so bear with me. I am using NW.JS 0.24.0 and the pre-built binaries aren't working. So I installed NPM, Python 2.7 and installed nw-gyp with the npm command. 

Now I am trying to build greenworks doing: 
cd greenworks
nw-gyp configure --target=0.24.0 --arch=x64
nw-gyp build

The configure one seems to work fine, but calling build results in errors, see below:
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.4.0
gyp info using node@6.11.1 | win32 | x64
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Invalid Version: undefined
gyp ERR! stack     at new SemVer (C:\Users\Calamitron\AppData\Roaming\npm\node_modules\nw-gyp\node_modules\semver\semver.js:279:11)
gyp ERR! stack     at compare (C:\Users\Calamitron\AppData\Roaming\npm\node_modules\nw-gyp\node_modules\semver\semver.js:566:10)
gyp ERR! stack     at Function.gt (C:\Users\Calamitron\AppData\Roaming\npm\node_modules\nw-gyp\node_modules\semver\semver.js:595:10)
gyp ERR! stack     at C:\Users\Calamitron\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:67:22
gyp ERR! stack     at C:\Users\Calamitron\AppData\Roaming\npm\node_modules\nw-gyp\node_modules\graceful-fs\graceful-fs.js:78:16
gyp ERR! stack     at tryToString (fs.js:456:3)
gyp ERR! stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Calamitron\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build"
gyp ERR! cwd C:\Users\Calamitron\Desktop\greenworks-0.10.0
gyp ERR! node -v v6.11.1
gyp ERR! nw-gyp -v v3.4.0
gyp ERR! This is a bug in `nw-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nwjs/nw-gyp/issues>

Any idea  what this means? Or if there are any newer pre-built binaries I could use with NW.JS 0.24? 

Thanks

**Comment by koobazaur** [comment]
Ok found an answer here:

https://github.com/nwjs/nw-gyp/issues/107
