### ISSUE TITLE
Confusing Node Module error

### ISSUE THREAD

**Issue by quantumproducer** [greenheartgames/greenworks#161]
osx64.node was compiled against node module version 57..
but this version of node needs 53? Is this saying version 57 needs 53?

I have tried rm -rf node modules and running npm build and I still get this error.

Uncaught Error: The module '/Users/quantum/ele/electron-quick-start/lib/greenworks-osx64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/quantum/ele/electron-quick-start/greenworks.js:12:18)
    at Object.<anonymous> (/Users/quantum/ele/electron-quick-start/greenworks.js:133:3)

**Comment by quantumproducer** [comment]
I tried upgrading node to 8.6.0, same issue.

**Comment by hokein** [comment]
@quantumproducer Could you please provide the version of Greenworks and Electron you are using?

**Comment by quantumproducer** [comment]
"devDependencies": {
    "electron": "~1.6.2"
  }

greenworks:  v0.11.0

**Comment by quantumproducer** [comment]
I missed there were other releases further down the page. I installed the one for electron 1.6.1. Now my code runs this:

<script>
  var greenworks = require('./greenworks');
  var f = greenworks.initAPI();
  document.write(f);
  console.log(f);
  </script>
</body>


"false" logged into the console.

**Comment by hokein** [comment]
@quantumproducer Yes, Greenworks prebuilt v0.11.0 only works for electron v1.8.0, it is not compatible with electron 1.6.2. You should use the corresponding Greenworks version accordingly.

Have you started the Steam client before running you application? You can use `greeenworks.init()` API, it will provides more detailed diagnostics.
