### ISSUE TITLE
does the greenworks installed from npm work?

### ISSUE THREAD

**Issue by id4alex** [greenheartgames/greenworks#176]
Does the greenworks installed from npm work? Or it only works for the self-build version? It seems that nodejs still has problem when importing greenworks installed by npm after adding sdkencryptedappticket64.dll (lib)/steam_api.dll (lib)/steam_api64.dll (lib) into the lib folder.

module.js:664
  return process.dlopen(module, path._makeLong(filename));

Error: The specified module could not be found.
\\?\C:\Users\id4al\node_modules\greenworks\lib\greenworks-win64.node
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\id4al\node_modules\greenworks\greenworks.js:17:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

**Comment by hokein** [comment]
No, greenworks can't be installed from npm. To make it work, you need to download the prebuilt binary and put it into your project directory.

**Comment by id4alex** [comment]
@hokein,  thanks, already solved the problem.
