### ISSUE TITLE
Can't Load module in nw.js 26.6, SDK1.41 

### ISSUE THREAD

**Issue by Baccanno** [greenheartgames/greenworks#177]
Hi,
I'm pretty sure I had the issue before and managed to get through it but I'm stuck for some time now.
I have an `Uncaught Error: The specified module could not be found.` although my dll and and .lib are as always in the same folder.

I also make sure I took the libs from the correct release.

Any hint ?

The full stack 
```
\\?\[...]\win64\data\lib\greenworks-win64.node
module.js:713 Uncaught Error: Le module spécifié est introuvable.
\\?\[...]\win64\data\lib\greenworks-win64.node
    at Object.Module._extensions..node (module.js:713:18)
    at Module.load (module.js:585:32)
    at tryModuleLoad (module.js:528:12)
    at Function.Module._load (module.js:520:3)
    at Module.require (module.js:610:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([...]\win64\data\greenworks.js:17:18)
    at Module._compile (module.js:666:30)
    at Object.Module._extensions..js (module.js:683:10)
    at Module.load (module.js:585:32)
indexScript.js:16 assert.js:42
Uncaught AssertionError [ERR_ASSERTION]: path must be a string
assert.js:42 Uncaught AssertionError: path must be a string
    at Module.require (module.js:609:3)
    at require (internal/module.js:11:18)
    at self.require (<anonymous>:11:26)
```

**Comment by Baccanno** [comment]
It finds the module somehow, but it feels to me the "version" is not correct as if I delete the .lib file I get a direct `Uncaught Error: Cannot find module './lib/greenworks-win32'`

**Comment by Baccanno** [comment]
My bad I forgot to put the now needed : sdkencryptedappticket libs. is this documented ?

**Comment by hokein** [comment]
@Baccanno Yeah, the encryptedappticket library is required since v0.8.0, and it is documented in https://github.com/greenheartgames/greenworks/blob/master/docs/quick-start-nwjs.md#using-prebuilt-binaries-in-nwjs-quick-start.
