### ISSUE TITLE
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.

### ISSUE THREAD

**Issue by plutopair** [greenheartgames/greenworks#186]
When trying to do an `npm i` for a project that recently added greenworks we are seeing the following:

`-- greenworks@0.12.0  (git+https://github.com/greenheartgames/greenworks.git#a77eebaad09b8c5163102a5b33c99c76250c7f3d)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@~1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@~1.3.1 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> greenworks@0.12.0 install D:\src\GITROOT\PlutoVR\wrapper-win32\node_modules\greenworks
> node-gyp rebuild

D:\src\GITROOT\PlutoVR\wrapper-win32\node_modules\greenworks>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\src\GITROOT\PlutoVR\wrapper-win32\node_modules\greenworks
gyp ERR! node -v v6.13.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm WARN greenworks@0.12.0 No repository field.
npm WARN greenworks@0.12.0 No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! greenworks@0.12.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the greenworks@0.12.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the greenworks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs greenworks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls greenworks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\src\GITROOT\PlutoVR\wrapper-win32\node_modules\greenworks\npm-debug.log
Rebuilding Greenworks

> Pluto@2018.5.1-beta.21 rebuild-greenworks D:\src\GITROOT\PlutoVR\wrapper-win32
> electron-rebuild -f -m node_modules/greenworks

Cleaning Greenworks directory
Warning: Please use as subcommand: electron-builder install-app-deps
electron-builder 19.16.0
Rebuilding native production dependencies for win32:x64
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@~1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@~1.3.1 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})

Please help!

**Comment by plutopair** [comment]
[npm-debug.log](https://github.com/greenheartgames/greenworks/files/1858293/npm-debug.log)

**Comment by plutopair** [comment]
I'm using git-bash on Windows 10 on this computer. It has Visual Studio 2017 Community and Python 2.7. As a test I manually removed ~/.node-gyp and things still fail the same way.
