### ISSUE TITLE
Uncaught Error: error: 126

### ISSUE THREAD

**Issue by hooker99** [greenheartgames/greenworks#193]
Hello. I have an error in console (F12):

 Uncaught Error: error: 126\\?\C:\Users\user\greenworks-master\lib\greenworks-win64.node

I'm testing this with the sample app. The URL/patch is correct. What's going on? 

Greenworks Test
NW.js version: 0.26.6.
NW.js architecture: x64.
Node.js version: v9.1.0.
Greenworks.js version: .

Full error:

VM271:11 Uncaught Error: error: 126\\?\C:\Users\user\greenworks-master\lib\greenworks-win64.node
    at Object.Module._extensions..node (module.js:713:18)
    at Module.load (module.js:585:32)
    at tryModuleLoad (module.js:528:12)
    at Function.Module._load (module.js:520:3)
    at Module.require (module.js:610:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\greenworks-master\greenworks.js:17:18)
    at Module._compile (module.js:666:30)
    at Object.Module._extensions..js (module.js:683:10)
    at Module.load (module.js:585:32)
Module._extensions..node @ module.js:713
Module.load @ module.js:585
tryModuleLoad @ module.js:528
Module._load @ module.js:520
Module.require @ module.js:610
require @ internal/module.js:11
(anonymous) @ C:\Users\user\greenworks-master\greenworks.js:17
Module._compile @ module.js:666
Module._extensions..js @ module.js:683
Module.load @ module.js:585
tryModuleLoad @ module.js:528
Module._load @ module.js:520
Module.require @ module.js:610
require @ internal/module.js:11
self.require
self.require @ VM271:11
(anonymous) @ index.html:16
VM271:11 Uncaught Error: error: 126\\?\C:\Users\user\greenworks-master\lib\greenworks-win64.node
    at Object.Module._extensions..node (module.js:713:18)
    at Module.load (module.js:585:32)
    at tryModuleLoad (module.js:528:12)
    at Function.Module._load (module.js:520:3)
    at Module.require (module.js:610:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\greenworks-master\greenworks.js:17:18)
    at Module._compile (module.js:666:30)
    at Object.Module._extensions..js (module.js:683:10)
    at Module.load (module.js:585:32)

**Comment by hooker99** [comment]
Thanks I forgot copy "sdkencryptedappticket.dll". But now I have another problem: "Error on initializing steam API.", what it mean :P? 

Greenworks Test
NW.js version: v0.26.6.
NW.js architecture: x64.
Node.js version: v9.3.0.
Greenworks.js version: 0.12.0.

**Comment by hokein** [comment]
I can't tell the reason with this limited error message. Can you try to use `greeenworks.init()` API instead of `greenworks.initAPI()`, which provides more context when initialization fails.

**Comment by hooker99** [comment]
Yea I changed it:

Uncaught Error: **Steam initialization failed. Steam is not running.**
    at EventEmitter.greenworks.init (C:\Users\user\greenworks-master\greenworks.js:102:11)
    at testSteamAPI (chrome-extension://deneojijmcbkglffallgahellijjmjm/main.js:14:21)
    at HTMLDocument.<anonymous> (chrome-extension://deneojijmcbkglffallgahellijjmjm/main.js:59:60)

What it mean? Steam.exe is running and I'm logged on...

**Comment by hokein** [comment]
hmm, that's weird... Maybe try to upgrade your steam client and retry?

**Comment by hooker99** [comment]
Yea I updated, restarted... And nothing :/

Uncaught Error: Steam initialization failed. Steam is not running.
    at EventEmitter.greenworks.init (C:\Users\user\greenworks-master\greenworks.js:102:11)

Error means that Steam.exe is not running? It can not be anything else? 

What can I do now? :( Send my sample to you?

**Comment by mrdev023** [comment]
Which libraries have you copied?
Do you respect your CPU architecture (32bit or 64bit)?

**Comment by hokein** [comment]
I'm closing it now, feel free to reopen it.

**Comment by hooker99** [comment]
Sorry for the late reply #vacation 

I figured it out, everything is fine, but... 

1) I need to be logged in to Steam (greenworks is not working offline mode), I think it's okay, but ...
2) ... if I close Steam **and change to another user** (second account), I have an error in console (F12):

`Uncaught Error: Steam initialization failed. Steam is not running.
    at EventEmitter.greenworks.init (C:\Users\airem\Desktop\Projekty\Play With Me\data\Achievements\greenworks-master\greenworks.js:105:11)`

To fix it I need to restart my PC. It possible to restart (steamworks) it another way or it's a bug?

Greenworks Test (Windows 10 64bit)
NW.js version: 0.30.5.
NW.js architecture: x64.
Node.js version: v10.1.0.
Greenworks.js version: 0.13.0.
