### ISSUE TITLE
Steam Achievments in Visual Novel Maker

### ISSUE THREAD

**Issue by korytoombs** [greenheartgames/greenworks#233]
I'm getting the black screen of death. 
(ie. game loads but only shows black screen, but heck I can experience it using my GTX 1060 graphics card at least.) 

Following this tutorial: 

https://forums.rpgmakerweb.com/index.php?threads/advanced-users-tutorial-unlockable-steam-achievements.100313/ 

Using these files: 

greenworks-v0.14.0-nw-v0.31.5-win-x64 

nwjs-v0.26.6-win-x64 

steamworks_sdk_141

**Comment by hokein** [comment]
Looks like you are using a mismatched nw.js version, please use the corresponding nw.js version, in your case, use nw.js-v0.31.5-win-x64.

**Comment by korytoombs** [comment]
I think I was using the wrong greenworks actually (according to the tutorial.)
Trying to change to greenworks-v0.12.0-nw-v0.26.6-win-x64

I did a test run and console error still.  (Tutorial might be wrong about which version to use.)

Uncaught Error: The specified module could not be found.
\\?\C:\Users\user\Desktop\steamworks_sdk_141\sdk\tools\ContentBuilder\content\Norilsk\lib\greenworks-win64.node
    at Object.Module._extensions..node (module.js:713:18)
    at Module.load (module.js:585:32)
    at tryModuleLoad (module.js:528:12)
    at Function.Module._load (module.js:520:3)
    at Module.require (module.js:610:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\Desktop\steamworks_sdk_141\sdk\tools\ContentBuilder\content\Norilsk\greenworks.js:17:18)
    at Module._compile (module.js:666:30)
    at Object.Module._extensions..js (module.js:683:10)
    at Module.load (module.js:585:32)
