### ISSUE TITLE
Error with DLL Loading

### ISSUE THREAD

**Issue by FlowingSPDG** [greenheartgames/greenworks#235]
Hi. I have an issue when Im using it with Electron v4.0.0.

When I try `./node_modules/.bin/electron .`,It crashes with following error :
```Uncaught Exception:
Error: A dynamic link library (DLL) initialization routine failed.
\\?\F:\repo\my-mmservice\client\node_modules\greenworks\lib\greenworks-win64.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\repo\my-mmservice\client\node_modules\greenworks\greenworks.js:17:18)```

but `electron-packager . BUILD --platform=win32 --arch=x64 --overwrite --asar --prune`
works well,please help me!

**Comment by FlowingSPDG** [comment]
Sorry, I was using wrong electron version because of package.json settings. Closing
