### ISSUE TITLE
Trying to clone greenworks repository

### ISSUE THREAD

**Issue by KonScyence** [greenheartgames/greenworks#249]
Hi, I'm trying to clone the greenworks repository using the command provided in the documentation: `npm install --save --ignore-scripts git+https://github.com/greenheartgames/greenworks.git`

But I have this error:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\konsc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'greenheartgames/greenworks'
1 verbose cli ]
2 info using npm@6.13.0
3 info using node@v12.13.0
4 verbose npm-session 3e06306adee8f45b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for github:greenheartgames/greenworks Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/greenheartgames/greenworks.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 56ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
10 verbose stack     at onErrorNT (internal/child_process.js:456:16)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
11 verbose cwd C:\Users\konsc\Desktop\Nouveau dossier
12 verbose Windows_NT 10.0.17763
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\konsc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "greenheartgames/greenworks"
14 verbose node v12.13.0
15 verbose npm  v6.13.0
16 error code ENOENT
17 error syscall spawn git
18 error path git
19 error errno ENOENT
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t ssh://git@github.com/greenheartgames/greenworks.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ 1, true ]
```

Any solution?

Electron v.7.1.1
Node v.12.13.0
Npm v.6.13.0

**Comment by KonScyence** [comment]
Forget to install git on my new computer...
