### ISSUE TITLE
"greenworks-win64.node module not found" when the file is present in the directory

### ISSUE THREAD

**Issue by sameer-manek** [greenheartgames/greenworks#284]

**Comment by sameer-manek** [comment]
I also tried the same with nw js and got a similar error

**Comment by henggedaren** [comment]
You check nw.js version

**Comment by sameer-manek** [comment]
@henggedaren I did, and had the same issue.

**Comment by ittehgav** [comment]
I have set up greenworks with the prebuilt binaries for NW.js 0.33.3 and steamworks SDK 1.42, followed [these](https://github.com/greenheartgames/greenworks/blob/master/docs/quick-start-nwjs.md) instructions, it works fine on linux but on windows, with a similar setup, i get

`Uncaught Error: The specified procedure could not be found.
\\?\C:\Users\ittehgav\Desktop\game\dist\game-1.0.0-win-x64\lib\greenworks-win64.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1206:18)
    at Module.load (node:internal/modules/cjs/loader:991:32)
    at Function.Module._load (node:internal/modules/cjs/loader:831:14)
    at Module.require (node:internal/modules/cjs/loader:1015:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\ittehgav\Desktop\game\dist\game-1.0.0-win-x64\greenworks.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1161:10)
    at Module.load (node:internal/modules/cjs/loader:991:32)
    at Function.Module._load (node:internal/modules/cjs/loader:831:14)`

**Comment by henggedaren** [comment]
> @hokein
> I have set up greenworks with the prebuilt binaries for NW.js 0.33.3 and steamworks SDK 1.42, followed [these](https://github.com/greenheartgames/greenworks/blob/master/docs/quick-start-nwjs.md) instructions, it works fine on linux but on windows, with a similar setup, i get
> 
> `Uncaught Error: The specified procedure could not be found.
> \?\C:\Users\ittehgav\Desktop\game\dist\game-1.0.0-win-x64\lib\greenworks-win64.node
> 
> ```
> at Object.Module._extensions..node (node:internal/modules/cjs/loader:1206:18)
> 
> at Module.load (node:internal/modules/cjs/loader:991:32)
> 
> at Function.Module._load (node:internal/modules/cjs/loader:831:14)
> 
> at Module.require (node:internal/modules/cjs/loader:1015:19)
> 
> at require (node:internal/modules/cjs/helpers:92:18)
> 
> at Object.<anonymous> (C:\Users\ittehgav\Desktop\game\dist\game-1.0.0-win-x64\greenworks.js:17:18)
> 
> at Module._compile (node:internal/modules/cjs/loader:1126:14)
> 
> at Object.Module._extensions..js (node:internal/modules/cjs/loader:1161:10)
> 
> at Module.load (node:internal/modules/cjs/loader:991:32)
> 
> at Function.Module._load (node:internal/modules/cjs/loader:831:14)`
> ```



> @hokein
> 我已经用NW.js 0.33.3和steamworks SDK 1.42的预编译二进制文件设置了greenworks，按照[这些](https://github.com/greenheartgames/greenworks/blob/master/docs/quick-start-nwjs.md)说明，它在linux上工作正常，但在Windows上，使用类似的设置，我得到了
> 
> `未捕获的错误：找不到指定的过程。
> \？\ C：\ Users \ ittehgav \ Desktop \ game \ dist \ game-1.0.0-win-x64 \ lib \ greenworks-win64.node
> 
> ```
> at Object.Module._extensions..node (node:internal/modules/cjs/loader:1206:18)
> 
> at Module.load (node:internal/modules/cjs/loader:991:32)
> 
> at Function.Module._load (node:internal/modules/cjs/loader:831:14)
> 
> at Module.require (node:internal/modules/cjs/loader:1015:19)
> 
> at require (node:internal/modules/cjs/helpers:92:18)
> 
> at Object.<anonymous> (C:\Users\ittehgav\Desktop\game\dist\game-1.0.0-win-x64\greenworks.js:17:18)
> 
> at Module._compile (node:internal/modules/cjs/loader:1126:14)
> 
> at Object.Module._extensions..js (node:internal/modules/cjs/loader:1161:10)
> 
> at Module.load (node:internal/modules/cjs/loader:991:32)
> 
> at Function.Module._load (node:internal/modules/cjs/loader:831:14)`
> ```

Sorry, I have the same problem in window

![QQ截图20210126131913](https://user-images.githubusercontent.com/37524430/105803818-319f5680-5fd9-11eb-9a5c-e204c62cfc4d.png)

**Comment by michaelpelletier** [comment]
Having this same issue, myself. @sameer-manek @ittehgav did you end up figuring out a workaround?

**Comment by francois-n-dream** [comment]
Same issue here too. Mac worked. Windows not.

I copied all kinds of ``.dll``, ``.dylib`` and ``.node`` files into the ``node_modules/greenworks/lib`` directory.

I didn't know that it was necessary to use the ``electron-rebuild``. On Mac it somewhat worked without and I thought it was for the final build (I am using ``electron-builder`` for that).

It's all in here:
https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-electron.md

**Comment by connorsleight** [comment]
Any update on this? I cant get past the `The specified module could not be found.` error when it tries to find the .node file

**Comment by MikalDev** [comment]
Sometimes this is an issue with mismatched sdk, node versions, electron / os versions. I suggest using the prebuilt binaries and verifying that all the versions are aligned. If you try again, document all the versions of SDK, node, electron used and a link to the prebuilt binary being used.

**Comment by MikalDev** [comment]
I did a quick test, the last working version of Electron that works for me with the prebuilt is https://www.electronjs.org/releases/stable?version=12 (12.2.3).

To make this work I had to change main.js (see comments with ***). These are potentially security holes, so use/review with caution.

```javascript
function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      // *** Add next two lines ***
      nodeIntegration: true,
      contextIsolation: false,
      preload: path.join(__dirname, 'preload.js')
    }
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.

// *** Add next line ***
app.allowRendererProcessReuse = false
app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})
```
It looks like for Electron versions after this, the GreenWorks binary interface source files need to be changed to be NAPI/context-aware, see this issue:

https://github.com/electron/electron/issues/18397

**Comment by connorsleight** [comment]
I think I'll just leave greenworks/steamworks out of my project. With the latest release being over 3 years ago and none of the newer versions of things like electron supported, it's not really viable to use in new projects

**Comment by ceifa** [comment]
> I think I'll just leave greenworks/steamworks out of my project. With the latest release being over 3 years ago and none of the newer versions of things like electron supported, it's not really viable to use in new projects

greenworks do works great yet, I'm using it on electron 16 (almost) without problems, check my fork if you want some important updates

**Comment by connorsleight** [comment]
@ceifa What version of the steamworks sdk do you use with your fork? 1.41? 1.50?

**Comment by MikalDev** [comment]
@ceifa Great work in that fork! I'm going to build locally and try Electron 16 again. I also let the prebuild site owner know about the fork.

**Comment by connorsleight** [comment]
I tried that fork with 1.42 of the sdk and the .node file from the v0.14 release (i couldnt find that file in your repo) and i still get the issue with it not finding the .node file as a module

**Comment by MikalDev** [comment]
@connorsleight you will need to use his repo to build a new node file with the version of electron you want to use.

I successfully built the node files on windows and ran the electron quick start with Electron 16.0.5 and Steam 1.50 SDK. The test app successfully connected to Steam.

I used the 'Building with electron-rebuild' method to build the node files and run the test app. Note that instead of doing npm install --save --ignore-scripts git+https://github.com/greenheartgames/greenworks.git, I did npm install --save --ignore-scripts git+https://github.com/ceifa/greenworks.git to get the fork.

I had to do one change to the test app in main.js before doing npm start to test the app:

```javascript
function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      // *** Add next two lines to get require() to work
      nodeIntegration: true,
      contextIsolation: false,
      preload: path.join(__dirname, 'preload.js')
    }
  })
  ```

@ceifa thanks for the updated fork!

**Comment by ceifa** [comment]
> @ceifa What version of the steamworks sdk do you use with your fork? 1.41? 1.50?

The latest, 1.53a

**Comment by michaelpelletier** [comment]
@ceifa @MikalDev - Thanks for the fork & help on this! Is there a way to generate the `*.node` files for systems I don't have? Using `electron-rebuild` works for the current system, but if I wanted to generate for Mac + Windows + Linux, is there a way to do that?

**Comment by ceifa** [comment]
> @ceifa @MikalDev - Thanks for the fork & help on this! Is there a way to generate the `*.node` files for systems I don't have? Using `electron-rebuild` works for the current system, but if I wanted to generate for Mac + Windows + Linux, is there a way to do that?

Idk if cross-building is possible, but today I build for the three using a github action, where I can specify the OS to be used.

https://docs.github.com/pt/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

If you are on windows you can use the WSL2 to build for linux.

**Comment by kkortes** [comment]
Two days ago I spent a good 8 hours on trying to get `greenworks` to work with _the newest version of things_. 

By chance I saw @ceifa's `steamworks.js`: https://github.com/ceifa/steamworks.js and gave it a try. 5 minutes later I properly booted up my Electron game with access to the Steamworks SDK-features & Steam overlay.

You are a champ @ceifa !
