### ISSUE TITLE
binding.gyp linking to /osx32 folder

### ISSUE THREAD

**Issue by podrivo** [greenheartgames/greenworks#295]
Hello!

I've been trying different builds the past days and came across this.
I was able to build in Windows, but when went to macOS, I got this error:

```
Building module: greenworks, Completed: 0ld: warning: directory not found for option '-L/Library/WebServer/Documents/_dev/greenworks-test/node_modules/greenworks/deps/steamworks_sdk/redistributable_bin/osx32/'
ld: warning: directory not found for option '-L/Library/WebServer/Documents/_dev/greenworks-test/node_modules/greenworks/deps/steamworks_sdk/public/steam/lib/osx32/'
ld: library not found for -lsteam_api
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/greenworks-osx64.node] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Library/WebServer/Documents/_dev/greenworks-test/node_modules/greenworks'.
Error: `make` failed with exit code: 2

Error: node-gyp failed to rebuild '/Library/WebServer/Documents/_dev/greenworks-test/node_modules/greenworks'.
Error: `make` failed with exit code: 2

    at ModuleRebuilder.rebuildNodeGypModule (/Library/WebServer/Documents/_dev/greenworks-test/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Rebuilder.rebuildModuleAt (/Library/WebServer/Documents/_dev/greenworks-test/node_modules/electron-rebuild/lib/src/rebuild.js:190:9)
    at async Rebuilder.rebuild (/Library/WebServer/Documents/_dev/greenworks-test/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /Library/WebServer/Documents/_dev/greenworks-test/node_modules/electron-rebuild/lib/src/cli.js:146:9
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Error is saying that it can't find the `/osx32` folder, but I guess this folder shouldn't exist? I wasn't sure, so I went and edit the `bindings.gyp` and removed the number 32:

https://github.com/greenheartgames/greenworks/blob/4fbf54accf4bde777e6f3b80e1ecfb86683b1568/binding.gyp#L48-L49

And after this edit, the build passed!

```
⠦ Building module: greenworks, Completed: 026 warnings generated.
⠧ Building module: greenworks, Completed: 0  SOLINK_MODULE(target) Release/greenworks-osx64.node
⠇ Building module: greenworks, Completed: 0  ACTION binding_gyp_copy_binaries_target_Copy_Binaries lib
⠏ Building module: greenworks, Completed: 0  TOUCH Release/obj.target/copy_binaries.stamp
✔ Rebuild Complete
✨  Done in 51.71s.
```

**Comment by qq253498229** [comment]
Oh my God, thank you so much, your answer has helped me so much!
