### ISSUE TITLE
Cannot build NWJS with greenworks

### ISSUE THREAD

**Issue by jamesid** [greenheartgames/greenworks#30]
I am running into issues trying to build NWJS.  

Running nw-gyp build produces this error:

```
C:\greenworks>nw-gyp build /m
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.12.7 | win32 | ia32
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/m',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
  minizip.vcxproj -> C:\greenworks\build\Release\\minizip.lib
  zlib.vcxproj -> C:\greenworks\build\Release\\zlib.lib
  greenworks_async_workers.cc
..\src\greenworks_async_workers.cc(192): error C2143: syntax error : missing ')
' before '{' [C:\greenworks\build\greenworks-win32.vcxproj]
..\src\greenworks_async_workers.cc(192): error C2059: syntax error : ')' [C:\gr
eenworks\build\greenworks-win32.vcxproj]
..\src\greenworks_async_workers.cc(192): error C2143: syntax error : missing ';
' before '{' [C:\greenworks\build\greenworks-win32.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\James\AppData\Roaming\npm\no
de_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\James\\AppData\\Roaming\\npm\\node_modules\\
nw-gyp\\bin\\nw-gyp.js" "build" "/m"
gyp ERR! cwd C:\greenworks
gyp ERR! node -v v0.12.7
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
```

**Comment by hokein** [comment]
Have you configured the build files with a specided nw.js version using `nw-gyp configure` command? There is a tutorial guide on https://github.com/greenheartgames/greenworks#nwjs-building-steps.

**Comment by jamesid** [comment]
I've configured the builds according to the build steps, but to no avail.  This is the configuration I started with:

```
C:\greenworks>nw-gyp configure --target=0.12.3 --arch=ia32
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.12.7 | win32 | ia32
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn python
gyp info spawn args [ 'C:\\Users\\James\\AppData\\Roaming\\npm\\node_modules\\nw
-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\greenworks\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\James\\AppData\\Roaming\\npm\\node_modules\\nw
-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\James\\.nw-gyp\\0.12.3\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\James\\.nw-gyp\\0.12.3',
gyp info spawn args   '-Dmodule_root_dir=C:\\greenworks',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\greenworks\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

C:\greenworks>nw-gyp build
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.12.7 | win32 | ia32
child_process: customFds option is deprecated, use stdio instead.
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  zip.c
  iowin32.c
  unzip.c
  ioapi.c
  minizip.vcxproj -> C:\greenworks\build\Release\\minizip.lib
  trees.c
  gzlib.c
  inffast.c
  uncompr.c
  inftrees.c
  gzread.c
  infback.c
  gzclose.c
  compress.c
..\..\..\deps\zlib\gzlib.c(186): warning C4244: '=' : conversion from '__int64'
 to 'long', possible loss of data [C:\greenworks\build\deps\zlib\zlib.vcxproj]
..\..\..\deps\zlib\gzlib.c(311): warning C4244: '=' : conversion from '__int64'
 to 'long', possible loss of data [C:\greenworks\build\deps\zlib\zlib.vcxproj]
..\..\..\deps\zlib\gzlib.c(406): warning C4244: '=' : conversion from '__int64'
 to 'long', possible loss of data [C:\greenworks\build\deps\zlib\zlib.vcxproj]
  zutil.c
  crc32.c
  adler32.c
  inflate.c
  gzwrite.c
  deflate.c
  zlib.vcxproj -> C:\greenworks\build\Release\\zlib.lib
  greenworks_async_workers.cc
  greenworks_unzip.cc
  greenworks_utils.cc
  steam_async_worker.cc
  greenworks_zip.cc
  greenworks_workshop_workers.cc
  greenworks_api.cc
..\src\greenworks_async_workers.cc(192): error C2143: syntax error : missing ')
' before '{' [C:\greenworks\build\greenworks-win32.vcxproj]
..\src\greenworks_async_workers.cc(192): error C2059: syntax error : ')' [C:\gr
eenworks\build\greenworks-win32.vcxproj]
..\src\greenworks_async_workers.cc(192): error C2143: syntax error : missing ';
' before '{' [C:\greenworks\build\greenworks-win32.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\James\AppData\Roaming\npm\no
de_modules\nw-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\James\\AppData\\Roaming\\npm\\node_modules\\
nw-gyp\\bin\\nw-gyp.js" "build"
gyp ERR! cwd C:\greenworks
gyp ERR! node -v v0.12.7
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
```

ive also tried various combinations of versions of NWJS ( 0.12.0, 0.12.1, 0.12.2 ) and arch (ia32 and x64 ).  They all error at this point:

```
  greenworks_api.cc
..\src\greenworks_async_workers.cc(192): error C2143: syntax error : missing ')
' before '{' [C:\greenworks\build\greenworks-win32.vcxproj]
..\src\greenworks_async_workers.cc(192): error C2059: syntax error : ')' [C:\gr
eenworks\build\greenworks-win32.vcxproj]
..\src\greenworks_async_workers.cc(192): error C2143: syntax error : missing ';
' before '{' [C:\greenworks\build\greenworks-win32.vcxproj]
```

**Comment by hokein** [comment]
Which version of Visual Studio are you using? It's required VS 2013.

**Comment by jamesid** [comment]
I was using VS 2012.  Upgrading to VS 2013 did the trick.

Thank you so very much!

**Comment by janpetersen** [comment]
Just to add a note on this:

It will compile on VS 2012, if you change the following method from:

    void ClearAchievementWorker::HandleOKCallback() {
      NanScope();
      callback->Call(0, {});
    }

to:

    void ClearAchievementWorker::HandleOKCallback() {
      NanScope();
      callback->Call(0, NULL);
    }


For some reason, the compiler stubles on that "{ }" thing. A NULL will do. Don't know if it breaks anything, though. But since we did not use Achievements, it didn't matter. ;)
